# Generated by Django 5.0.1 on 2024-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('actual_output', models.TextField()),
                ('time_taken', models.FloatField()),
            ],
        ),
    ]
